server:
  port: 9090
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful
  tomcat:
    basedir: /tmp/batch
    
spring:
  application:
    name: seojin-batch
  jackson:
    time-zone: Asia/Seoul
    default-property-inclusion: NON_NULL
  config:
    use-legacy-processing: true            
  profiles:
    include: default-app, default-db
  freemarker:
    checkTemplateLocation: false
  main:
   # allow-bean-definition-overriding: true  //bean 중복오류 발생시
    allow-circular-references: true    
  batch:
    job:
      enabled: false
  quartz:
    job-store-type: jdbc
    scheduler-name: seojin-scheduler
    overwrite-existing-jobs: true
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 10
          jobStore:
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 6000
            dataSource: primary
#            dataSource:  quartzPrimary
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#          dataSource:
#            quartzPrimary:
#              driver: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#              URL: jdbc:log4jdbc:mariadb://seojin-dev-setos-db-00.ctsmdpvbvpot.ap-northeast-2.rds.amazonaws.com:3816/TEST_INFO
#              user: info
#              password: info
#              provider: hikaricp

jasypt:
  encryptor:
    bean: encryptorBean   
      
logging:
  config: classpath:log/logback_local.xml
